services:

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    environment:
      TZ: Asia/Seoul
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - certbot
    networks:
      - re-caring

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  spring-blue:
    image: brianchoi506/re-caring:latest
    container_name: recaring-blue
    restart: on-failure:3
    env_file: .env
    environment:
      SPRING_PROFILES_ACTIVE: dev
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis
    networks:
      - re-caring

  spring-green:
    image: brianchoi506/re-caring:latest
    container_name: recaring-green
    restart: on-failure:3
    env_file: .env
    environment:
      SPRING_PROFILES_ACTIVE: dev
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8081:8080"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis
    networks:
      - re-caring

  redis:
    image: redis:7-alpine
    container_name: recaring-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - re-caring

volumes:
  redis-data:

networks:
  re-caring:
    driver: bridge
