services:

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    environment:
      TZ: Asia/Seoul
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - certbot
    networks:
      - re-caring

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  spring-blue:
    image: brianchoi506/re-caring:latest
    container_name: recaring-blue
    restart: on-failure:3
    env_file: .env
    environment:
      SPRING_PROFILES_ACTIVE: dev
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8080:8080"
    labels:
      - "monitor=true"
    volumes:
      - ./logs/blue:/var/log/re-caring
    depends_on:
      - redis
    networks:
      - re-caring

  spring-green:
    image: brianchoi506/re-caring:latest
    container_name: recaring-green
    restart: on-failure:3
    env_file: .env
    environment:
      SPRING_PROFILES_ACTIVE: dev
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8081:8080"
    labels:
      - "monitor=true"
    volumes:
      - ./logs/green:/var/log/re-caring
    depends_on:
      - redis
    networks:
      - re-caring

  redis:
    image: redis:7-alpine
    container_name: recaring-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - re-caring

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    restart: always
    command: [
      "run",
      "--server.http.listen-addr=0.0.0.0:12345",
      "--storage.path=/var/lib/alloy/data",
      "/etc/alloy/config.alloy"
    ]
    volumes:
      - ./monitoring/alloy/config.alloy:/etc/alloy/config.alloy
      - ./logs:/var/log/re-caring:ro # API 서버 로그 읽기용
      - /var/run/docker.sock:/var/run/docker.sock
      - alloy-data:/var/lib/alloy/data
    networks:
      - re-caring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
      - "--storage.tsdb.retention.time=15d"
    volumes:
      - prometheus-data:/var/lib/prometheus/data
    networks:
      - re-caring

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: always
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ./monitoring/loki/loki-config.yml:/etc/loki/loki-config.yml
      - loki-data:/var/lib/loki/data
    networks:
      - re-caring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana/data
    depends_on:
      - prometheus
      - loki
    networks:
      - re-caring

volumes:
  redis-data:
  alloy-data:
  prometheus-data:
  loki-data:
  grafana-data:


networks:
  re-caring:
    driver: bridge
