server {
    listen 80;
    server_name re-caRing.com

     location /.well-known/acme-challenge/ {
        root /var/www/certbot;
     }

     location / {
        return 301 https://$host$request_uri;
     }
}

server {
    listen 443 ssl;
    server_name re-caRing.com

    ssl_certificate     /etc/letsencrypt/live/re-caRing.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/re-caRing.com/privkey.pem;
}