








jwt:
  secretKey: ${JWT_KEY}
  access:
    expiration: 3600000
    header: Authorization
  refresh:
    expiration: 1209600000
    header: Authorization-refresh

coolsms:
  api-key: ${COOLSMS_API_KEY}
  api-secret: ${COOLSMS_API_SECRET}
  sender: ${COOLSMS_SENDER}
