spring:
  application:
    name: recaring
  profiles:
    active: local
  config:
    import: "optional:file:.env[.properties]"

logging:
  level:
    root: ERROR
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: INFO
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO

