spring:
  application:
    name: recaring
  config:
    import: "optional:file:.env[.properties]"

logging:
  level:
    root: INFO

firebase:
  enabled: ${FIREBASE_ENABLED:false}
  service-account-json-base64: ${FIREBASE_SERVICE_ACCOUNT_JSON_BASE64:}

