package com.recaring.alert.implement;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Component;
import org.springframework.web.client.RestClient;

import java.util.List;
import java.util.Map;

@Slf4j
@Component
@RequiredArgsConstructor
public class GitHubPrCreator {

    private final RestClient restClient;

    @Value("${alert.github.token}")
    private String githubToken;

    @Value("${alert.github.owner}")
    private String owner;

    @Value("${alert.github.repo}")
    private String repo;

    public String createPr(String alertName, List<String> commands, String analysisText) {
        log.info("[GitHub PR : 생성 시작]: alertName={}", alertName);
        try {
            String title = "fix: Auto-fix for alert — " + alertName;
            String body = buildPrBody(alertName, commands, analysisText);

            Map<String, Object> payload = Map.of(
                    "title", title,
                    "body", body,
                    "head", "auto-fix/" + sanitizeBranchName(alertName),
                    "base", "main"
            );

            String url = String.format("https://api.github.com/repos/%s/%s/pulls", owner, repo);

            String response = restClient.post()
                    .uri(url)
                    .header(HttpHeaders.AUTHORIZATION, "Bearer " + githubToken)
                    .header(HttpHeaders.ACCEPT, "application/vnd.github+json")
                    .contentType(MediaType.APPLICATION_JSON)
                    .body(payload)
                    .retrieve()
                    .body(String.class);

            log.info("[GitHub PR : 생성 완료]: alertName={}", alertName);
            return response != null ? response : "PR created but no response body";
        } catch (Exception e) {
            log.warn("[GitHub PR : 생성 실패]: alertName={} | error={}", alertName, e.getMessage());
            return "Failed to create PR: " + e.getMessage();
        }
    }

    private String buildPrBody(String alertName, List<String> commands, String analysisText) {
        return String.format("""
                ## Auto-fix PR for Alert: %s

                ### AI Analysis
                %s

                ### Fix Commands Applied
                ```bash
                %s
                ```

                > Generated by Recaring Alert LLM Investigation System
                """,
                alertName,
                analysisText,
                String.join("\n", commands)
        );
    }

    private String sanitizeBranchName(String alertName) {
        return alertName.toLowerCase().replaceAll("[^a-z0-9-]", "-");
    }
}
